version: "3.9"

services:
  wildfly:
    build: 
      context: ./docker/wildfly
      args:
        WILDFLY_USER: ${WILDFLY_USER}
        WILDFLY_PASS: ${WILDFLY_PASS}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        DB_NAME: ${DB_NAME}
    container_name: "wildfly-lab4"
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - "./build/libs/:/opt/jboss/wildfly/standalone/deployments"
    depends_on:
      - "postgres"

  postgres:
    image: postgres:15.1
    ports:
      - "5432:5432"
    container_name: "postgres-lab4"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
